### ISSUE TITLE
Install gives errors

### ISSUE THREAD

**Issue by dman776** [sharkrf/spk-srv#1]
trying to install spk-srv on a pi (raspbian Jessie).
getting the following errors:

pi@k5dlq-pi1:~ $ go get github.com/sharkrf/spk-srv
# github.com/sharkrf/spk-srv
gocode/src/github.com/sharkrf/spk-srv/spk-srv.go:31: undefined: _bindata
gocode/src/github.com/sharkrf/spk-srv/spk-srv.go:121: undefined: Asset
gocode/src/github.com/sharkrf/spk-srv/spk-srv.go:240: undefined: strings.Compare

**Comment by nonoo** [comment]
Readme has been fixed, thanks for reporting the issue.
